name: Deploy to Nexus

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and deploy
      run: mvn clean deploy
      env:
        MVN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MVN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}